# Change these first
owner: jmassardo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DXRF
    url: http://dxrf.com
  - name: DXRF - SSL
    url: https://dxrf.com
  - name: Massardo Electronics
    url: http://massardoelectronics.com
  - name: Massardo Electronics - SSL
    url: https://massardoelectronics.com
  - name: Massardo Family
    url: http://massardofamily.com
  - name: Massardo Family - SSL
    url: https://massardofamily.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: dxrf.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Website Monitoring"
  introMessage: 'I use [Upptime](https://github.com/upptime/upptime) and GitHub Actions to monitor all my personal websites and projects. I monitor the HTTP and SSL connections separately since I have multiple domain names that point to the same GitHub Pages site. Read more about that here: [NGINX URL rewrites](https://dxrf.com/blog/2021/03/16/nginx-url-rewrites/)'
  navbar:
    - title: Home
      href: /
    - title: Blog
      href: /blog
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
